/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestOffRouteImport } from './routes/testOff'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionsAuctionUuidRouteImport } from './routes/auctions.$auctionUuid'
import { Route as AuctionsAuctionUuidBetRouteImport } from './routes/auctions.$auctionUuid_.bett'

const TestOffRoute = TestOffRouteImport.update({
  id: '/testOff',
  path: '/testOff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionUuidRoute = AuctionsAuctionUuidRouteImport.update({
  id: '/auctions/$auctionUuid',
  path: '/auctions/$auctionUuid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionUuidBetRoute = AuctionsAuctionUuidBetRouteImport.update({
  id: '/auctions/$auctionUuid_/bet',
  path: '/auctions/$auctionUuid/bet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/testOff': typeof TestOffRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bet': typeof AuctionsAuctionUuidBetRoute
}
export interface FileRoutesByTo {
  '/testOff': typeof TestOffRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRoute
  '/auctions': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bet': typeof AuctionsAuctionUuidBetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/testOff': typeof TestOffRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid_/bet': typeof AuctionsAuctionUuidBetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/testOff'
    | '/auctions/$auctionUuid'
    | '/auctions/'
    | '/auctions/$auctionUuid/bet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/testOff'
    | '/auctions/$auctionUuid'
    | '/auctions'
    | '/auctions/$auctionUuid/bet'
  id:
    | '__root__'
    | '/testOff'
    | '/auctions/$auctionUuid'
    | '/auctions/'
    | '/auctions/$auctionUuid_/bet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TestOffRoute: typeof TestOffRoute
  AuctionsAuctionUuidRoute: typeof AuctionsAuctionUuidRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  AuctionsAuctionUuidBetRoute: typeof AuctionsAuctionUuidBetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testOff': {
      id: '/testOff'
      path: '/testOff'
      fullPath: '/testOff'
      preLoaderRoute: typeof TestOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid': {
      id: '/auctions/$auctionUuid'
      path: '/auctions/$auctionUuid'
      fullPath: '/auctions/$auctionUuid'
      preLoaderRoute: typeof AuctionsAuctionUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid_/bet': {
      id: '/auctions/$auctionUuid_/bet'
      path: '/auctions/$auctionUuid/bet'
      fullPath: '/auctions/$auctionUuid/bet'
      preLoaderRoute: typeof AuctionsAuctionUuidBetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TestOffRoute: TestOffRoute,
  AuctionsAuctionUuidRoute: AuctionsAuctionUuidRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  AuctionsAuctionUuidBetRoute: AuctionsAuctionUuidBetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
