/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as TestOffRouteImport } from './routes/testOff'

const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOffRoute = TestOffRouteImport.update({
  id: '/testOff',
  path: '/testOff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auctions': typeof AuctionsRoute
  '/testOff': typeof TestOffRoute
}
export interface FileRoutesByTo {
  '/auctions': typeof AuctionsRoute
  '/testOff': typeof TestOffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auctions': typeof AuctionsRoute
  '/testOff': typeof TestOffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auctions' | '/testOff'
  fileRoutesByTo: FileRoutesByTo
  to: '/auctions' | '/testOff'
  id: '__root__' | '/auctions' | '/testOff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuctionsRoute: typeof AuctionsRoute
  TestOffRoute: typeof TestOffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testOff': {
      id: '/testOff'
      path: '/testOff'
      fullPath: '/testOff'
      preLoaderRoute: typeof TestOffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuctionsRoute: AuctionsRoute,
  TestOffRoute: TestOffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
